Fix I18N issues
brainstormforce/read-meter pull request #22
Opened 2021-08-19 21:05 UTC by alexclassroom

- delete Plugin Name header's dot at the end.
- Modify the current text domain to equal plugin slug.
- Adding necessary text domain for localizable strings.
- Fix wrong text domain from bsf_rt_textdomain to read-meter.

2021-08-20 03:57 UTC, RajkiranBagal approved these changes

2021-08-20 06:50 UTC, vrundakansara requested changes

2021-08-20 06:50 UTC, vrundakansara commented on includes/bsf-rt-user-manual.php
> +		echo __( 'How to Use? </label><br><br>
We can separate out each and every statement in translation and keep the HTML out of the PHP script.
Step 1,2,3 in a single `__()` and rest of the statement in other `__()`
```php
<b><?php __( 'Step 1' ); ?></b> <?php __( ':Under the <i>General Settings</i> Tab, select post types to display the Read Time and Progress bar. Select Words Per Minute and set other options if required.' ) ?> <br><br>
```

2025-07-10 18:01 UTC, alexclassroom commented
Closed this old and no one cares PR, I will submit a new PR for the same issues.

2025-07-10 18:01 UTC, closed without merging